### ISSUE TITLE
Unrecognized MacOSX SDK version (after installing Xcode 7.1)

### ISSUE THREAD

**Issue by luzpaz** [scribusproject/homebrew-scribus#23]
See:
* http://bugs.scribus.net/view.php?id=13554
* https://github.com/Homebrew/homebrew/issues/46362

**Comment by luzpaz** [comment]
Possible fix: https://github.com/scribusproject/scribus/pull/40

**Comment by luzpaz** [comment]
Passing  ```"-DCMAKE_OSX_DEPLOYMENT_TARGET=#{MacOS.version}"``` to Cmake fixed it

I get this output though:

CMake Warning at /usr/local/Cellar/cmake/3.4.0/share/cmake/Modules/Platform/Darwin-Initialize.cmake:97 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.10' but the matching SDK does not exist
  at:

   "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk"

  Instead using SDK:

   "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk".
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.4.0/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:18 (include)
  CMakeLists.txt:42 (PROJECT)

**Comment by afincato** [comment]
Sorry for re-opening this, but I'm having the same problem and I don't know how to patch it with your suggestion. How do I pass `-DCMAKE_OSX_DEPLOYMENT_TARGET=#{MacOS.version}`? 

In some other related and closed issues it is suggested to flag cmake in a different way, but I don't know how to do that as well.

```
CMAKE_OSX_DEPLOYMENT_TARGET is '10.11' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:47 (PROJECT)
```

Thanks for your help!

**Comment by luzpaz** [comment]
* What version of xCode do you have installed? 
* What MacOS version are you running?
* Are you using Homebrew to build Scribus trunk? I ask because the fix is already updated in the scribus homebrew tap so you shouldn't theoretically encountering this. (see https://github.com/scribusproject/homebrew-scribus/blob/master/scribus.rb#L52)

To answer your question you can  pass `-DCMAKE_OSX_DEPLOYMENT_TARGET=10.10.5` (or the version you have installed) like that to cmake, but the `#{MacOS.version}` variable should take care of that for you.

**Comment by afincato** [comment]
* I realised only now that I have only the command line tools version of xCode installed, and not the whole package: is that creating this problem?
* Mac OS X 10.11.4
* Using homebrew, yes

**Comment by luzpaz** [comment]
what version of xcode CLI ?

**Comment by afincato** [comment]
```
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by luzpaz** [comment]
do a `brew gist-logs scribus` and send the links

**Comment by afincato** [comment]
Here it is — https://gist.github.com/48a3d60e29fbab71e42eedbd873ffa45

**Comment by luzpaz** [comment]
ok.. 
quick and dirty answer: install the full xCode 
long term: need to ascertain if Scribus on OSX can be built solely with xCode Command Line Tools and if so hack Cmake to look for it

**Comment by afincato** [comment]
OK thanks! 

(Also, I saw there is compiled versions of the nightly builds now, so will look into it — http://forums.scribus.net/index.php/topic,2029.0.html)

**Comment by luzpaz** [comment]
per machomebrew on Freenode:
> It is because brew compiles from source if there is no binary package

ref: https://github.com/scribusproject/homebrew-scribus/issues/6

**Comment by luzpaz** [comment]
@afincato if you haven't installed full xCode yet...please `brew update && brew upgrade --all` and run `brew install --HEAD scribus --verbose` again. 
I've added a fix 31aab67691af9ddf445f6c744b8338755d48d611 that will allow compile with xCode CLT

**Comment by afincato** [comment]
Worked like a charm! Thanks for your patience.

**Comment by luzpaz** [comment]
great. thanks for the ticket and testing. 
Cheers :+1:
